[package]
name = "chromadb"
authors = ["Anush008"]
description = "A Rust client for  ChromaDB. www.trychroma.com/"
edition = "2021"
license = "https://github.com/Anush008/chromadb-rs/blob/master/LICENSE"
version = "0.1.0"
repository = "https://github.com/Anush008/chromadb-rs/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.72"

[dependencies.reqwest]
features = ["json"]
version = "0.11"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1.0.97"
