[package]
name = "chromadb"
authors = ["Anush008"]
description = "A Rust client for  ChromaDB. www.trychroma.com/"
edition = "2021"
license = "MIT"
version = "0.1.3"
repository = "https://github.com/Anush008/chromadb-rs/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"

[dependencies.reqwest]
features = ["json"]
version = "0.11"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dev-dependencies.tokio]
version = "1"
features = ["macros"]
