[package]
name = "chroma-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.72"

[dependencies.reqwest]
features = ["json"]
version = "0.11"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1.0.97"
