name: Cargo tests
'on':
  push:
    branches:
      - master
      - beta
  pull_request:
    branches:
      - master
      - beta
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ChromaDB
        uses: CakeCrusher/chroma@v1.0.3
      - name: Run tests
        run: cargo test
