name: Semantic Release
on:
  push:
    branches:
      - master
      - beta
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "🔧 setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "🔧 install npm@latest"
        run: npm i -g npm@latest

      - name: "📦 install dependencies"
        uses: bahmutov/npm-install@v1

      - name: "Semantic release🚀"
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
            npx semantic-release
  
      - name: "echo outputs"
        run: |
          echo "RELEASE_TAG: ${{ env.RELEASE_TAG }}"
          echo "RELEASE_VERSION: ${{ env.RELEASE_VERSION }}"
          echo "outputs.release-tag: ${{ steps.release.outputs.release-tag }}"
          echo "outputs.release-version: ${{ steps.release.outputs.release-version }}"
      
