name: "Cargo Tests"
on:
    pull_request:
      types:
        - opened
        - edited
        - synchronize
        - reopened
  
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ChromaDB
        uses: CakeCrusher/chroma@v1.0.3
      - name: Run tests
        run: cargo test